server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mariadb://localhost:3306/admin
    driver-class-name: org.mariadb.jdbc.Driver
    username: green
    password: green1234
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      #'[hibernate.default_batch_fetch_size]': 100
      "[hibernate.format_sql]": true
    show-sql: true

logging:
  level:
    "[site.hobbyup.class_final_back]": DEBUG
